class Solution {
public:
    string addBinary(string a, string b) 
    {
        int i=a.length()-1,j=b.length()-1;
        string r="";
        bool c=false;
        while(i>=0&&j>=0)
        {
            if((a[i]=='0'&&b[j]=='1')||(a[i]=='1'&&b[j]=='0'))
            {
                if(c)
                {
                    r+='0';
                    c=true;
                }
                else
                {
                    r+="1";
                }
            }
           else if(a[i]=='1'&&b[j]=='1')
            {
                if(c)
                {
                    r+='1';
                }
                else
                {
                    r+="0";
                }
                c=true;
            }
            else if(a[i]=='0'&&b[j]=='0')
            {
                if(c)
                {
                    r+="1";
                    c=false;
                }
                else
                r+="0";
            }
            --i;--j;
        }
        while(i>=0)
        {
            if(a[i]=='0')
            {
                if(c)
                {
                    r+="1";
                    c=false;
                }
                else
                r+='0';
            }
            else
            {
                if(c)
                {
                    r+="0";
                    c=true;
                }
                else
                r+="1";
            }
            --i;
        }
        while(j>=0)
        {
            if(b[j]=='0')
            {
                if(c)
                {
                    r+="1";
                    c=false;
                }
                else
                r+='0';
            }
            else
            {
                if(c)
                {
                    r+="0";
                    c=true;
                }
                else
                r+="1";
            }
            --j;
        }
        if(c)
        r+="1";
        reverse(r.begin(),r.end());
        return r;
    }
};